# Site settings
title: C++ Blog

author:
  name: Patrick Hession
  email: your-email@domain.com
description: "A website."

# Build settings
remote_theme: jekyll/minima

plugins:
- jekyll-remote-theme

