# Site settings
title:Digital Rain C++ Blog

author:
  name: patrick Hession
  email: your-email@domain.com
description: "A blog."

# Build settings
remote_theme: jekyll/minima

plugins:
- jekyll-remote-theme

